image:
- Ubuntu1804

clone_depth: 25

build: off

init:
- sh: sudo apt install -yq --no-install-suggests --no-install-recommends liblapack-dev openmpi-bin libopenmpi-dev libscalapack-openmpi-dev > /dev/null

install:
- cmake -B build -S .
- cmake --build build -j

test_script:
- cd tests/build
- cmake ..
- cmake --build . -j
- ctest --output-on-failure

