image:
#- Visual Studio 2017
- Ubuntu

environment:
  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

clone_depth: 3

build: off

init:
- cmd: set PATH=%MINGW_DIR%;%PATH%

#- sh: sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test" > /dev/null
#- sh: sudo apt-get -yq update > /dev/null
- sh: sudo apt-get install -yq --no-install-suggests --no-install-recommends liblapack-dev > /dev/null
- sh: sudo apt-get install -yq --no-install-suggests --no-install-recommends libmetis-dev libparmetis-dev libscotch-dev libptscotch-dev libatlas-base-dev openmpi-bin libopenmpi-dev  > /dev/null
- sh: sudo apt-get install -yq --no-install-suggests --no-install-recommends libmumps-dev > /dev/null

install:
# Lapack95
- cd $APPVEYOR_BUILD_FOLDER/LAPACK95
- make -s double -C SRC

# MUMPS
- sh: cd $APPVEYOR_BUILD_FOLDER/MUMPS
- sh: make -s d
  
test_script:
- cd $APPVEYOR_BUILD_FOLDER/tests/bin

- cmd: cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
- sh: cmake ..

- cmake --build .
- ctest -V
