# gfortran >= 6 is required.
# Ubuntu >= 16.04 needed to build or use MUMPS with MPI
language: c
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true

os:
# - osx  # works, just saving resources
- linux

env: FC=gfortran-6

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: ['gfortran-6','liblapack-dev','openmpi-bin','libopenmpi-dev','libscalapack-dev']
    # MUMPs build, needs Ubuntu 16.04 'libatlas-base-dev','openmpi-bin','libopenmpi-dev',


matrix:
  include:
  - os: linux
#  - os: osx
#    env: FC=gfortran
#    before_install:
#    - brew install gcc > /dev/null
#    - brew install lapack > /dev/null
#    - brew install open-mpi > /dev/null

    

install: ./build_gnu_noMKL.sh  
  
script:
- cd $TRAVIS_BUILD_DIR/tests/build

- cmake ..
- cmake --build .

- ctest --output-on-failure

